"use strict";
exports.__esModule = true;
var Product_1 = require("./Product");
var ProductService_1 = require("./ProductService");
var _poductService = new ProductService_1.ProductService();
var result;
result = _poductService.getById(3);
var p = new Product_1.Product();
p.id = 2;
p.name = "iphone 11";
p.category = "Telefon";
p.price = 15000;
_poductService.saveProduct(p);
//_poductService.deleteProduct(result);
result = _poductService.getProducts();
console.log(result);
